spring:
  graphql:
    graphiql:
      enabled: true

  application:
    name: project-practice-api
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:project-practice-api}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:31702005}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}



server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  root-user: ${MINIO_ROOT_USER:demorgan}
  root-password: ${MINIO_ROOT_PASSWORD:password}

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    enabled: true
    path: /v3/api-docs

client:
  ip: ${CLIENT_IP:http://62.233.43.154}

company:
  default:
    email: ${COMPANY_DEFAULT_EMAIL:iknt@psu.ru}
    password: ${COMPANY_DEFAULT_PASSWORD:eBxYWr/PlJ8fB%Z:'vCt__[[S#{O|'}

logging:
  level:
    root: info
  file:
    name: ./project-practice.log