spring:
  application:
    name: project-practice-api
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:project-practice-api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:31702005}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  root-user: ${MINIO_ROOT_USER:demorgan}
  root-password: ${MINIO_ROOT_PASSWORD:password}

logging:
  level:
    root: info
  file:
    name: ./project-practice.log